name: hayidev
description: HayiDev
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
flutter:
  uses-material-design: true
