name: hayidev
description: HayiDev — sesli sohbet + 51 sistem
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  in_app_purchase: ^3.2.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/
